name: GoonCraft
main: com.miauwrijn.gooncraft.Plugin
version: 0.3.0
api-version: '1.21'
authors: ["Miauwrijn"]
description: The Minecraft plugin your server never knew it needed
commands:
  gooncraft:
    description: GoonCraft main command
    usage: /<command> <stats|achievements|leaderboard|reload>
    aliases:
      - gc
  buttfinger:
    description: Buttfinger someone nearby
    usage: /<command> <player>
    aliases:
      - bf
  penis:
    description: Penis stat commands
    usage: /<command> <size|girth|bbc>
    aliases:
      - pp
  genitals:
    description: Toggle your genitals visibility (gender-aware)
    usage: /<command> [toggle]
    aliases:
      - geni
      - expose
  viagra:
    description: Get a viagra pill
    usage: /<command>
    permission: gooncraft.viagra
  fart:
    description: Let one rip
    usage: /<command>
  poop:
    description: Drop a deuce
    usage: /<command>
  piss:
    description: Take a leak (requires genitals toggle)
    usage: /<command>
  gender:
    description: View or change your gender
    usage: /<command> [change]
  boobs:
    description: Boob stat commands
    usage: /<command> <size|perkiness|jiggle>
    aliases:
      - tits
      - breasts
  skillpoints:
    description: Open skill points shop
    usage: /<command>
    aliases:
      - sp
      - skills
  resetskillpoints:
    description: Reset your skill points and perks
    usage: /<command> [confirm]
    permission: gooncraft.skillpoints.reset

permissions:
  gooncraft.reload:
    description: Allows reloading the config
    default: op
  gooncraft.viagra:
    description: Allows spawning viagra pills
    default: op
  gooncraft.size.set:
    description: Allows setting player sizes
    default: op
  gooncraft.girth.set:
    description: Allows setting player girths
    default: op
  gooncraft.bbc.set:
    description: Allows setting BBC status
    default: op
  gooncraft.boobs.set:
    description: Allows setting player boob sizes
    default: op
  gooncraft.skillpoints.reset:
    description: Allows resetting skill points
    default: op
