name: GoonCraft
main: com.miauwrijn.gooncraft.Plugin
version: 0.1.0
api-version: '1.21'
authors: ["Miauwrijn"]
description: The Minecraft plugin your server never knew it needed
commands:
  buttfinger:
    description: Buttfinger someone nearby
    usage: /<command> <player>
    aliases:
      - bf
    permission-message: You do not have permission to use this command
  penis:
    description: Penis commands
    usage: /<command> <size|girth|bbc|toggle>
    aliases:
      - pp
    permission-message: You do not have permission to use this command
  viagra:
    description: Get a viagra pill
    usage: /<command>
    permission: gooncraft.viagra
    permission-message: You do not have permission to use this command
