name: GoonCraft
main: com.miauwrijn.gooncraft.Plugin
version: 0.2.0
api-version: '1.21'
authors: ["Miauwrijn"]
description: The Minecraft plugin your server never knew it needed
commands:
  gooncraft:
    description: GoonCraft main command
    usage: /<command> <stats|achievements|leaderboard|reload>
    aliases:
      - gc
  buttfinger:
    description: Buttfinger someone nearby
    usage: /<command> <player>
    aliases:
      - bf
  penis:
    description: Penis commands
    usage: /<command> <size|girth|bbc|toggle>
    aliases:
      - pp
  viagra:
    description: Get a viagra pill
    usage: /<command>
    permission: gooncraft.viagra
  fart:
    description: Let one rip
    usage: /<command>
  poop:
    description: Drop a deuce
    usage: /<command>
  piss:
    description: Take a leak (requires penis toggle)
    usage: /<command>

permissions:
  gooncraft.reload:
    description: Allows reloading the config
    default: op
  gooncraft.viagra:
    description: Allows spawning viagra pills
    default: op
  gooncraft.size.set:
    description: Allows setting player sizes
    default: op
  gooncraft.girth.set:
    description: Allows setting player girths
    default: op
  gooncraft.bbc.set:
    description: Allows setting BBC status
    default: op
